# assignment 1 question 2 22m0421(sumit kumar)

In [308]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [309]:
data = pd.read_csv('file1.csv')

In [310]:
data.head()

attr1  attr2  attr3  attr4  attr5  attr6  attr7   atr8  attr9  attr10  \
0   42.9   26.0   31.5   13.1   10.4   18.8   14.1  106.2   71.5    32.5   
1   43.7   28.5   33.5   14.0   11.8   20.6   15.1  110.5   79.0    34.4   
2   40.1   28.2   33.3   13.9   10.9   19.7   14.1  115.1   83.2    33.4   
3   44.3   29.9   34.0   13.9   11.2   20.9   15.0  104.5   77.8    31.0   
4   41.0   26.8   32.2   14.9   10.6   17.8   14.0  107.5   78.0    36.0   

   attr11  attr12  attr13  attr14  attr15  attr16  attr17  attr18  
0    26.0    34.5    36.5    23.5    16.5      21       1    65.6  
1    28.0    36.5    37.5    24.5    17.0      23       1    71.8  
2    28.8    37.0    37.3    21.9    16.9      28       1    80.7  
3    26.2    37.0    34.8    23.0    16.6      23       1    72.6  
4    29.0    34.5    35.0    22.0    16.5      23       1    71.0

In [311]:
data.shape

(446, 18)

In [312]:
describe = open("desc1.txt")
describe = describe.read()
print(describe)

Body measurements of 446 physically active individuals.

Description
Body girth measurements and skeletal diameter measurements, as well as age, weight and gender, are given for 446 physically active individuals - 223 men and 223 women. 

Format
A data frame with 446 observations on the following 18 variables.

attr1
A numerical vector, respondent's biacromial diameter in centimeters.

attr2
A numerical vector, respondent's biiliac diameter (pelvic breadth) in centimeters.

attr3
A numerical vector, respondent's bitrochanteric diameter in centimeters.

attr4
A numerical vector, respondent's elbow diameter in centimeters, measured as sum of two elbows.

attr5
A numerical vector, respondent's wrist diameter in centimeters, measured as sum of two wrists.

attr6
A numerical vector, respondent's knee diameter in centimeters, measured as sum of two knees.

attr7
A numerical vector, respondent's ankle diameter in centimeters, measured as sum of two ankles.

attr8
A numerical vector, responden

In [313]:
data.rename(
    columns={"attr1": "biacromial diameter", "attr2": "biiliac diameter", "attr3": "bitrochanteric diameter",
    "attr4" :"elbow diameter","attr5" : "wrist diameter", "attr6" : "knee diameter", "attr7":"ankle diameter",
    "atr8" : "shoulder girth", "attr9": "waist girth","attr10":"bicep girth","attr11": "forearm girth",
    "attr12":"knee girth", "attr13":"calf maximum girth","attr14":"ankle minimum girth","attr15":"wrist_min_girth",
    "attr16":"age", "attr17":"sex","attr18":"weight"},
    inplace=True,
)

In [314]:
data.head()

biacromial diameter  biiliac diameter  bitrochanteric diameter  \
0                 42.9              26.0                     31.5   
1                 43.7              28.5                     33.5   
2                 40.1              28.2                     33.3   
3                 44.3              29.9                     34.0   
4                 41.0              26.8                     32.2   

   elbow diameter  wrist diameter  knee diameter  ankle diameter  \
0            13.1            10.4           18.8            14.1   
1            14.0            11.8           20.6            15.1   
2            13.9            10.9           19.7            14.1   
3            13.9            11.2           20.9            15.0   
4            14.9            10.6           17.8            14.0   

   shoulder girth  waist girth  bicep girth  forearm girth  knee girth  \
0           106.2         71.5         32.5           26.0        34.5   
1           110.5         79.0         34.4           28.0        36.5   
2           115.1         83.2         33.4           28.8        37.0   
3           104.5         77.8         31.0           26.2        37.0   
4           107.5         78.0         36.0           29.0        34.5   

   calf maximum girth  ankle minimum girth  wrist_min_girth  age  sex  weight  
0                36.5                 23.5             16.5   21    1    65.6  
1                37.5                 24.5             17.0   23    1    71.8  
2                37.3                 21.9             16.9   28    1    80.7  
3                34.8                 23.0             16.6   23    1    72.6  
4                35.0                 22.0             16.5   23    1    71.0

check if any column in the dataframe contains any missing value or not

In [315]:
data.dtypes

biacromial diameter        float64
biiliac diameter           float64
bitrochanteric diameter    float64
elbow diameter             float64
wrist diameter             float64
knee diameter              float64
ankle diameter             float64
shoulder girth             float64
waist girth                float64
bicep girth                float64
forearm girth              float64
knee girth                 float64
calf maximum girth         float64
ankle minimum girth        float64
wrist_min_girth            float64
age                          int64
sex                          int64
weight                     float64
dtype: object

In [316]:
data.isna()

biacromial diameter  biiliac diameter  bitrochanteric diameter  \
0                  False             False                    False   
1                  False             False                    False   
2                  False             False                    False   
3                  False             False                    False   
4                  False             False                    False   
..                   ...               ...                      ...   
441                False             False                    False   
442                False             False                    False   
443                False             False                    False   
444                False             False                    False   
445                False             False                    False   

     elbow diameter  wrist diameter  knee diameter  ankle diameter  \
0             False           False          False           False   
1             False           False          False           False   
2             False           False          False           False   
3             False           False          False           False   
4             False           False          False           False   
..              ...             ...            ...             ...   
441           False           False          False           False   
442           False           False          False           False   
443           False           False          False           False   
444           False           False          False           False   
445           False           False          False           False   

     shoulder girth  waist girth  bicep girth  forearm girth  knee girth  \
0             False        False        False          False       False   
1             False        False        False          False       False   
2             False        False        False          False       False   
3             False        False        False          False       False   
4             False        False        False          False       False   
..              ...          ...          ...            ...         ...   
441           False        False        False          False       False   
442           False        False        False          False       False   
443           False        False        False          False       False   
444           False        False        False          False       False   
445           False        False        False          False       False   

     calf maximum girth  ankle minimum girth  wrist_min_girth    age    sex  \
0                 False                False            False  False  False   
1                 False                False            False  False  False   
2                 False                False            False  False  False   
3                 False                False            False  False  False   
4                 False                False            False  False  False   
..                  ...                  ...              ...    ...    ...   
441               False                False            False  False  False   
442               False                False            False  False  False   
443               False                False            False  False  False   
444               False                False            False  False  False   
445               False                False            False  False  False   

     weight  
0     False  
1     False  
2     False  
3     False  
4     False  
..      ...  
441   False  
442   False  
443   False  
444   False  
445   False  

[446 rows x 18 columns]

In [317]:
data.isnull().sum()

biacromial diameter        0
biiliac diameter           0
bitrochanteric diameter    0
elbow diameter             0
wrist diameter             0
knee diameter              0
ankle diameter             0
shoulder girth             0
waist girth                0
bicep girth                0
forearm girth              0
knee girth                 0
calf maximum girth         0
ankle minimum girth        0
wrist_min_girth            0
age                        0
sex                        0
weight                     0
dtype: int64

Let us move the weight column as the first column

In [318]:
data_weight = data.pop('weight')

data.insert(0,'weight', data_weight)

data.head()

weight  biacromial diameter  biiliac diameter  bitrochanteric diameter  \
0    65.6                 42.9              26.0                     31.5   
1    71.8                 43.7              28.5                     33.5   
2    80.7                 40.1              28.2                     33.3   
3    72.6                 44.3              29.9                     34.0   
4    71.0                 41.0              26.8                     32.2   

   elbow diameter  wrist diameter  knee diameter  ankle diameter  \
0            13.1            10.4           18.8            14.1   
1            14.0            11.8           20.6            15.1   
2            13.9            10.9           19.7            14.1   
3            13.9            11.2           20.9            15.0   
4            14.9            10.6           17.8            14.0   

   shoulder girth  waist girth  bicep girth  forearm girth  knee girth  \
0           106.2         71.5         32.5           26.0        34.5   
1           110.5         79.0         34.4           28.0        36.5   
2           115.1         83.2         33.4           28.8        37.0   
3           104.5         77.8         31.0           26.2        37.0   
4           107.5         78.0         36.0           29.0        34.5   

   calf maximum girth  ankle minimum girth  wrist_min_girth  age  sex  
0                36.5                 23.5             16.5   21    1  
1                37.5                 24.5             17.0   23    1  
2                37.3                 21.9             16.9   28    1  
3                34.8                 23.0             16.6   23    1  
4                35.0                 22.0             16.5   23    1

In [319]:
col = ['weight','biacromial diameter','biiliac diameter','bitrochanteric diameter','elbow diameter',
'wrist diameter', 'knee diameter', 'ankle diameter', 'shoulder girth','waist girth','bicep girth','forearm girth',
'knee girth','calf maximum girth','ankle minimum girth','age','sex','wrist_min_girth']

for col_ in col:
    data[col_] = (data[col_] - data[col_].mean())/data[col_].std()

data.head()


weight  biacromial diameter  biiliac diameter  bitrochanteric diameter  \
0 -0.252785             1.335451         -0.804699                -0.222173   
1  0.207356             1.597561          0.330903                 0.776710   
2  0.867881             0.418068          0.194631                 0.676822   
3  0.266729             1.794143          0.966841                 1.026431   
4  0.147983             0.712941         -0.441306                 0.127436   

   elbow diameter  wrist diameter  knee diameter  ankle diameter  \
0       -0.186075       -0.140547       0.020226        0.214426   
1        0.476076        1.319641       1.351138        1.010048   
2        0.402504        0.380949       0.685682        0.214426   
3        0.402504        0.693846       1.572956        0.930486   
4        1.138227        0.068052      -0.719170        0.134863   

   shoulder girth  waist girth  bicep girth  forearm girth  knee girth  \
0       -0.189144    -0.497447     0.343131       0.035890   -0.631196   
1        0.220316     0.169952     0.790262       0.741039    0.128624   
2        0.658343     0.543696     0.554930       1.023098    0.318579   
3       -0.351024     0.063168    -0.009867       0.106405    0.318579   
4       -0.065354     0.080966     1.166793       1.093613   -0.631196   

   calf maximum girth  ankle minimum girth  wrist_min_girth       age  \
0            0.160882             0.722286         0.286509 -0.968536   
1            0.506515             1.250038         0.643245 -0.761158   
2            0.437389            -0.122117         0.571898 -0.242715   
3           -0.426694             0.458410         0.357856 -0.761158   
4           -0.357567            -0.069341         0.286509 -0.761158   

        sex  
0  0.998878  
1  0.998878  
2  0.998878  
3  0.998878  
4  0.998878

In [320]:
data['sex'].sum()

5.684341886080802e-14

In [321]:
data.describe()

weight  biacromial diameter  biiliac diameter  \
count  4.460000e+02         4.460000e+02      4.460000e+02   
mean  -4.460806e-16        -5.098064e-16      1.449762e-15   
std    1.000000e+00         1.000000e+00      1.000000e+00   
min   -2.004288e+00        -2.039210e+00     -4.120658e+00   
25%   -7.927079e-01        -8.597166e-01     -5.775786e-01   
50%   -7.837636e-02        -4.062405e-02      3.564671e-02   
75%    7.231592e-01         7.702775e-01      6.488720e-01   
max    3.517401e+00         2.416653e+00      3.147197e+00   

       bitrochanteric diameter  elbow diameter  wrist diameter  knee diameter  \
count             4.460000e+02    4.460000e+02    4.460000e+02   4.460000e+02   
mean             -1.354173e-15    1.274516e-15    5.735323e-16   4.779435e-16   
std               1.000000e+00    1.000000e+00    1.000000e+00   1.000000e+00   
min              -2.819269e+00   -2.540391e+00   -2.539425e+00  -2.271900e+00   
25%              -6.716704e-01   -7.010820e-01   -7.663410e-01  -6.452303e-01   
50%               2.754767e-02   -1.125030e-01   -3.624744e-02  -5.371393e-02   
75%               6.768216e-01    7.703654e-01    6.938461e-01   6.117420e-01   
max               2.924308e+00    2.462530e+00    2.884127e+00   4.086901e+00   

       ankle diameter  shoulder girth   waist girth   bicep girth  \
count    4.460000e+02    4.460000e+02  4.460000e+02  4.460000e+02   
mean     2.549032e-16    8.284355e-16 -6.372581e-16 -5.098064e-16   
std      1.000000e+00    1.000000e+00  1.000000e+00  1.000000e+00   
min     -3.127188e+00   -2.122177e+00 -1.707663e+00 -2.033722e+00   
25%     -7.403211e-01   -8.438042e-01 -8.088994e-01 -8.570622e-01   
50%     -2.426113e-02    1.082471e-02 -1.370512e-01 -4.516686e-02   
75%      7.713611e-01    8.083196e-01  6.727261e-01  7.902617e-01   
max      2.680854e+00    2.534241e+00  3.213291e+00  2.649384e+00   

       forearm girth    knee girth  calf maximum girth  ankle minimum girth  \
count   4.460000e+02  4.460000e+02        4.460000e+02         4.460000e+02   
mean    1.656871e-15  8.921613e-16        2.357855e-15         1.688734e-15   
std     1.000000e+00  1.000000e+00        1.000000e+00         1.000000e+00   
min    -2.220586e+00 -2.720701e+00       -2.638745e+00        -3.024751e+00   
25%    -8.808034e-01 -6.691869e-01       -7.032004e-01        -6.366744e-01   
50%    -3.462501e-02 -6.133077e-02       -4.649772e-02        -6.934136e-02   
75%     8.732539e-01  6.130096e-01        6.447683e-01         6.035420e-01   
max     2.327623e+00  4.877500e+00        4.031972e+00         3.783246e+00   

       wrist_min_girth         age           sex  
count     4.460000e+02  446.000000  4.460000e+02  
mean     -5.098064e-16    0.000000  1.274516e-16  
std       1.000000e+00    1.000000  1.000000e+00  
min      -2.210646e+00   -1.279602 -9.988783e-01  
25%      -7.837002e-01   -0.761158 -9.988783e-01  
50%       1.119800e-03   -0.242715  0.000000e+00  
75%       7.145925e-01    0.586794  9.988783e-01  
max       2.498274e+00    3.593765  9.988783e-01

In [322]:
data_train = data.sample(frac=0.8 , random_state=150)
data_test = data.drop(data_train.index)

len(data_train), len(data_test)

(357, 89)

In [323]:
n_train = len(data_train.index)
print(n_train)
n_test = len(data_test)
print(n_test)

357
89


In [324]:
cols = list(np.arange(1,18))
x_train = data_train[data_train.columns[cols]]
x_test = data_test[data_test.columns[cols]]
x_train.head()

biacromial diameter  biiliac diameter  bitrochanteric diameter  \
101             1.630325          0.648872                 0.327213   
179             0.680177          0.421752                 0.477045   
82             -0.597607         -0.214186                -0.421950   
34             -0.401025         -0.532155                -1.021279   
66              1.433742         -0.668427                -0.721615   

     elbow diameter  wrist diameter  knee diameter  ankle diameter  \
101        0.917510        1.215342       0.907500        1.089610   
179        1.211800        0.485248      -0.053714       -0.024261   
82        -0.112503       -0.036247      -0.053714       -0.342510   
34        -0.406792       -0.557743      -1.310686       -0.660759   
66         0.770365        1.841136       1.055379       -0.183386   

     shoulder girth  waist girth  bicep girth  forearm girth  knee girth  \
101        0.867834     0.588189     0.625529       0.741039    0.698489   
179        0.934490     0.846250     0.790262       0.952583   -0.441241   
82        -0.503381    -0.150399    -1.280660      -1.127605   -0.897133   
34        -0.465292    -0.337271    -0.127533      -0.387199   -1.922890   
66         1.524875    -0.168196     1.331525       1.410930    0.736480   

     calf maximum girth  ankle minimum girth  wrist_min_girth       age  \
101            1.232344             1.936115         1.071329 -0.035338   
179           -0.668637            -0.227667         0.714593  1.519992   
82            -1.221650            -0.491543        -1.069089 -0.139026   
34            -1.912916            -1.652596        -0.783700 -0.657470   
66            -0.011934             0.247310         0.857287 -0.968536   

          sex  
101  0.998878  
179  0.998878  
82   0.998878  
34   0.998878  
66   0.998878

In [325]:
x_train.shape , x_test.shape

((357, 17), (89, 17))

In [326]:
y_train = data_train[data_train.columns[0]].to_numpy()
y_test = data_test[data_test.columns[0]].to_numpy()

y_train = y_train.reshape(357,1)
y_test = y_test.reshape(89,1)



In [327]:
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

In [328]:
x_test.shape , x_train.shape

((89, 17), (357, 17))

In [329]:
x_train

array([[ 1.63032467,  0.64887203,  0.32721258, ...,  1.07132885,
        -0.03533784,  0.99887829],
       [ 0.68017736,  0.42175154,  0.47704503, ...,  0.7145925 ,
         1.51999204,  0.99887829],
       [-0.59760695, -0.21418582, -0.42194969, ..., -1.06908925,
        -0.1390265 ,  0.99887829],
       ...,
       [-1.25288096, -0.30503402, -0.92139119, ..., -0.78370017,
        -1.07222443, -0.99887829],
       [-1.54775426,  0.14920696, -0.92139119, ..., -0.49831109,
        -0.76115845,  0.99887829],
       [-1.25288096, -0.5775786 , -0.17222893, ..., -1.63986741,
        -0.86484711, -0.99887829]])

In [330]:
# adding column of 1 at last

x_train = np.hstack((x_train, np.ones((x_train.shape[0],1),dtype=x_train.dtype)))
x_test = np.hstack((x_test, np.ones((x_test.shape[0],1),dtype=x_test.dtype)))

In [331]:
# solving least square

XTX = np.matmul(np.transpose(x_train),x_train)

print('XTX',XTX.shape)

XTY = np.matmul(np.transpose(x_train),y_train)

print('XTY' , XTY.shape)

beta = np.linalg.solve(XTX,XTY)

print('regression coefficient', beta)

XTX (18, 18)
XTY (18, 1)
regression coefficient [[ 0.05275255]
 [ 0.04785188]
 [ 0.04504678]
 [ 0.04666551]
 [ 0.04317002]
 [ 0.02410274]
 [ 0.06577171]
 [ 0.14489128]
 [ 0.41486179]
 [ 0.14824591]
 [ 0.03996369]
 [ 0.14618568]
 [ 0.05603409]
 [ 0.00732   ]
 [-0.0228953 ]
 [-0.07115854]
 [-0.11260651]
 [-0.00570047]]


# Doing 5-fold cross validation

In [332]:
lambdas = np.array([1e-5,1e-4,1e-3,1e-2,1e-1,1,10,100,1000,10000])

I = np.identity(XTX.shape[0])

for i in lambdas:
    print('lambda:',i,'cond(XTX+lambda I):', np.linalg.cond(XTX+i*I))

lambda: 1e-05 cond(XTX+lambda I): 269.94361545035105
lambda: 0.0001 cond(XTX+lambda I): 269.94193520241214
lambda: 0.001 cond(XTX+lambda I): 269.92513387767696
lambda: 0.01 cond(XTX+lambda I): 269.75723601549333
lambda: 0.1 cond(XTX+lambda I): 268.08971644394796
lambda: 1.0 cond(XTX+lambda I): 252.48611713227115
lambda: 10.0 cond(XTX+lambda I): 159.74562617379672
lambda: 100.0 cond(XTX+lambda I): 34.864301477766844
lambda: 1000.0 cond(XTX+lambda I): 4.819243262668257
lambda: 10000.0 cond(XTX+lambda I): 1.3868688221717098


In [333]:
seed = 150 

data_train_initial = data.sample(frac=0.8,random_state=seed)
data_test = data.drop(data_train_initial.index)

In [334]:
print(data_train_initial.shape)
print(data_test.shape)

(357, 18)
(89, 18)


defining the function for the R2 and MSE values

In [335]:
def Rq_and_MSE(data, beta, X, Y): 

  
  y_bar = 0.
  n = len(data)
  for i in range(n): 
    y_i= float(data.iat[i,0]) 
    y_bar += y_i

  y_bar /= n
  

  sigma_yy = 0
  for i in range(n): 
    y_i = float(data.iat[i,0]) 
    sigma_yy += (y_i-y_bar)**2

  
  sum_sq_residuals = 0.
  for i in range(n):  
    x_i = X[i,:] 
    y_i = Y[i] 

    y_pred_i = np.dot(x_i,beta) 
    e_i = y_i - y_pred_i 

    sum_sq_residuals += (e_i)**2

    
  
  R_sq = 1-sum_sq_residuals/sigma_yy
  MSE = sum_sq_residuals/n
  print('R^2 :',R_sq, ' MSE:',MSE)
  return R_sq, MSE

In [336]:
seeds = [200,250,300,350,400]
import scipy.linalg
train_R2_seeds = []
train_MSE_seed = []

colsx = list(np.arange(1,18))
res = [0]

for seed in seeds:
    data_train_final = data_train_initial.sample(frac=0.8 , random_state=seed)

    x_train = data_train_final[data_train_final.columns[colsx]].to_numpy()
    y_train = data_train_final[data_train_final.columns[res]].to_numpy()

    # adding ones col

    x_train = np.hstack((x_train,np.ones((x_train.shape[0],1),dtype=x_train.dtype)))
    
    train_R2_lambdas = []
    train_MSE_lambdas = []

    for lambda_ in lambdas:
        XTX = np.matmul(np.transpose(x_train),x_train)
        XTY = np.matmul(np.transpose(x_train),y_train)
        I = np.identity(x_train.shape[1])

        beta = scipy.linalg.solve(XTX + lambda_*I , XTY)
        
        print('lambda', lambda_)
        print('beta', beta)
        print(">>>>>>>>>>>>>>>>>>>>>>>>>")

        train_r2, train_mse = Rq_and_MSE(data_train_final,beta,x_train,y_train)
        train_R2_lambdas.append(train_r2)
        train_MSE_lambdas.append(train_mse)

    train_R2_seeds.append(np.array(train_R2_lambdas))
    train_MSE_seed.append(np.array(train_MSE_lambdas))

    print(">>>>>>>>>>>>>>>>>>>************")
    print("for next seed", seed)

lambda 1e-05
beta [[ 0.05336076]
 [ 0.03741211]
 [ 0.03943847]
 [ 0.0488236 ]
 [ 0.01453105]
 [ 0.03442717]
 [ 0.07403817]
 [ 0.17096492]
 [ 0.39310103]
 [ 0.14452957]
 [ 0.03159794]
 [ 0.16955121]
 [ 0.05584567]
 [-0.00192874]
 [-0.01352983]
 [-0.07603268]
 [-0.10078922]
 [-0.00462018]]
>>>>>>>>>>>>>>>>>>>>>>>>>
R^2 : [0.95422865]  MSE: [0.04513754]
lambda 0.0001
beta [[ 0.05336068]
 [ 0.0374122 ]
 [ 0.03943856]
 [ 0.04882347]
 [ 0.01453102]
 [ 0.03442721]
 [ 0.07403802]
 [ 0.17096494]
 [ 0.39310047]
 [ 0.14452943]
 [ 0.03159816]
 [ 0.16955116]
 [ 0.05584572]
 [-0.00192859]
 [-0.01352975]
 [-0.07603254]
 [-0.10078885]
 [-0.00462017]]
>>>>>>>>>>>>>>>>>>>>>>>>>
R^2 : [0.95422865]  MSE: [0.04513754]
lambda 0.001
beta [[ 0.05335987]
 [ 0.03741306]
 [ 0.03943949]
 [ 0.04882224]
 [ 0.01453075]
 [ 0.03442755]
 [ 0.07403661]
 [ 0.17096519]
 [ 0.39309493]
 [ 0.14452803]
 [ 0.03160042]
 [ 0.1695507 ]
 [ 0.05584627]
 [-0.00192712]
 [-0.0135289 ]
 [-0.07603122]
 [-0.10078521]
 [-0.00462011]]
>>>>

In [337]:
train_R2_seeds 

[array([[0.95422865],
        [0.95422865],
        [0.95422865],
        [0.95422865],
        [0.95422854],
        [0.95421763],
        [0.95345254],
        [0.93898336],
        [0.85239634],
        [0.37044814]]),
 array([[0.95618666],
        [0.95618666],
        [0.95618666],
        [0.95618666],
        [0.95618653],
        [0.9561738 ],
        [0.9553073 ],
        [0.93959073],
        [0.8510415 ],
        [0.37496374]]),
 array([[0.95248637],
        [0.95248637],
        [0.95248637],
        [0.95248637],
        [0.95248625],
        [0.95247505],
        [0.95169518],
        [0.93675501],
        [0.85093287],
        [0.37634793]]),
 array([[0.95088885],
        [0.95088885],
        [0.95088885],
        [0.95088884],
        [0.95088872],
        [0.95087657],
        [0.95004273],
        [0.93482049],
        [0.84697945],
        [0.36753061]]),
 array([[0.95408467],
        [0.95408467],
        [0.95408467],
        [0.95408467],
        [0.95408454],
  

In [338]:
mean_train_R2 = np.mean(train_R2_seeds,axis=0)  # for every lambda we took avg r2 for every seed
mean_train_R2

array([[0.95357504],
       [0.95357504],
       [0.95357504],
       [0.95357504],
       [0.95357491],
       [0.95356294],
       [0.95273883],
       [0.93753033],
       [0.85030907],
       [0.37221635]])

In [339]:
print('5-fold train R2 values:', mean_train_R2)

5-fold train R2 values: [[0.95357504]
 [0.95357504]
 [0.95357504]
 [0.95357504]
 [0.95357491]
 [0.95356294]
 [0.95273883]
 [0.93753033]
 [0.85030907]
 [0.37221635]]


In [340]:
best_lambda_index = np.argmax(mean_train_R2)

In [341]:
best_lambda = lambdas[best_lambda_index]
print(best_lambda)

1e-05


## now we have the best lambda from the 5 bold cross validation

with the use of this we will obtain the R2 and mse value on training data

In [342]:
data_train = data.sample(frac=0.8 , random_state=150)
data_test = data.drop(data_train.index)

n_train = len(data_train.index)
print(n_train)
n_test = len(data_test)
print(n_test)

cols = list(np.arange(1,18))
x_train = data_train[data_train.columns[cols]]
x_test = data_test[data_test.columns[cols]]

x_tn = x_train
d_tn = data_train

y_train = data_train[data_train.columns[0]].to_numpy()
y_test = data_test[data_test.columns[0]].to_numpy()

y_train = y_train.reshape(357,1)
y_test = y_test.reshape(89,1)

x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
x_test.shape , x_train.shape


357
89


((89, 17), (357, 17))

In [343]:
# adding column of 1 at last

x_train = np.hstack((x_train, np.ones((x_train.shape[0],1),dtype=x_train.dtype)))
x_test = np.hstack((x_test, np.ones((x_test.shape[0],1),dtype=x_test.dtype)))

In [344]:
XTX = np.matmul(np.transpose(x_train),x_train)
lambda_ = best_lambda
XTY = np.matmul(np.transpose(x_train),y_train)
I = np.identity(XTX.shape[0])

beta =scipy.linalg.solve(XTX+lambda_*I,XTY)
print('lambda:',lambda_)
print('beta:',beta)

lambda: 1e-05
beta: [[ 0.05275254]
 [ 0.04785189]
 [ 0.04504679]
 [ 0.0466655 ]
 [ 0.04317002]
 [ 0.02410274]
 [ 0.0657717 ]
 [ 0.14489129]
 [ 0.41486174]
 [ 0.1482459 ]
 [ 0.0399637 ]
 [ 0.14618568]
 [ 0.05603409]
 [ 0.00732001]
 [-0.02289529]
 [-0.07115853]
 [-0.11260648]
 [-0.00570047]]


## these are the coefficent from the question one
best lambda: 1e-05\
beta: [[ 2.32871204e-01]\
 [ 2.92873718e-01]\
 [ 3.03137158e-01]\
 [ 4.62614322e-01]\
 [ 6.06679125e-01]\
 [ 2.40123832e-01]\
 [ 7.05079818e-01]\
 [ 1.85897537e-01]\
 [ 4.97428622e-01]\
 [ 4.70082517e-01]\
 [ 1.89849206e-01]\
 [ 7.48317862e-01]\
 [ 2.60955248e-01]\
 [ 5.20561428e-02]\
 [-2.20121512e-01]\
 [-9.94170138e-02]\
 [-3.03102186e+00]\
 [-9.22644291e+01]]

In [345]:
b = np.array(beta)

In [346]:

sorted(b,key=abs,reverse=True)


[array([0.41486174]),
 array([0.1482459]),
 array([0.14618568]),
 array([0.14489129]),
 array([-0.11260648]),
 array([-0.07115853]),
 array([0.0657717]),
 array([0.05603409]),
 array([0.05275254]),
 array([0.04785189]),
 array([0.0466655]),
 array([0.04504679]),
 array([0.04317002]),
 array([0.0399637]),
 array([0.02410274]),
 array([-0.02289529]),
 array([0.00732001]),
 array([-0.00570047])]

In [347]:
data.head()

weight  biacromial diameter  biiliac diameter  bitrochanteric diameter  \
0 -0.252785             1.335451         -0.804699                -0.222173   
1  0.207356             1.597561          0.330903                 0.776710   
2  0.867881             0.418068          0.194631                 0.676822   
3  0.266729             1.794143          0.966841                 1.026431   
4  0.147983             0.712941         -0.441306                 0.127436   

   elbow diameter  wrist diameter  knee diameter  ankle diameter  \
0       -0.186075       -0.140547       0.020226        0.214426   
1        0.476076        1.319641       1.351138        1.010048   
2        0.402504        0.380949       0.685682        0.214426   
3        0.402504        0.693846       1.572956        0.930486   
4        1.138227        0.068052      -0.719170        0.134863   

   shoulder girth  waist girth  bicep girth  forearm girth  knee girth  \
0       -0.189144    -0.497447     0.343131       0.035890   -0.631196   
1        0.220316     0.169952     0.790262       0.741039    0.128624   
2        0.658343     0.543696     0.554930       1.023098    0.318579   
3       -0.351024     0.063168    -0.009867       0.106405    0.318579   
4       -0.065354     0.080966     1.166793       1.093613   -0.631196   

   calf maximum girth  ankle minimum girth  wrist_min_girth       age  \
0            0.160882             0.722286         0.286509 -0.968536   
1            0.506515             1.250038         0.643245 -0.761158   
2            0.437389            -0.122117         0.571898 -0.242715   
3           -0.426694             0.458410         0.357856 -0.761158   
4           -0.357567            -0.069341         0.286509 -0.761158   

        sex  
0  0.998878  
1  0.998878  
2  0.998878  
3  0.998878  
4  0.998878

In [348]:
x_tn.columns[0]

'biacromial diameter'

important atributes we get from strandardization 

ranking of the atributes

In [349]:
important_atributes = [8,9,11,7,16,6,12,0,1,3,2,4,10,5,14,13]
list_imp = []

for col_i in important_atributes:
    list_imp.append(x_tn.columns[col_i])

print(list_imp)

['waist girth', 'bicep girth', 'knee girth', 'shoulder girth', 'sex', 'ankle diameter', 'calf maximum girth', 'biacromial diameter', 'biiliac diameter', 'elbow diameter', 'bitrochanteric diameter', 'wrist diameter', 'forearm girth', 'knee diameter', 'wrist_min_girth', 'ankle minimum girth']
